#!/bin/bash

in_path()
{
    cmd=$1
    ourpath=$2
    result=1
    olfIFS=$IFS
    IFS=":"

    for directory in $ourpath
    do
        if [ -x $directory/$cmd ] ; then
            result=0
        fi
    done

    IFS=$oldIFS
    return $result
}

checkforCmdInPath()
{
    var=$1
    if [ "$var" != "" ] ; then
        if [ "${var%${var#?}}" = "/" ] ; then
            if [ ! -x $var ] ; then
                return 1
            fi
        elif ! in_path $var "$PATH" ; then
            return 2
        fi
    fi
}

if [ "$BASH_SOURCE" = "$0" ] ; then
    if [ $# -ne 1 ] ; then
        echo "Usage: $0 command" >&2
        exit 1
    fi

    checkforCmdInPath "$1"
    case $? in
        0 ) echo "$1 found in PATH"                ;;
        1 ) echo "$1 not found or not executable"  ;;
        2 ) echo "$1 not found in PATH"            ;;
    esac
fi

exit 0
